require('core.options')
require('core.keymaps')
require('core.diagnostic')
require('core.lsp_keymaps')

require('plugins.theme')
require('plugins.treesitter')
require('plugins.nvimtree')
require('plugins.lualine')
require('plugins.telescope')
require('plugins.gitsigns')

require('lsp.mason')
require('lsp.nvim-lspconfig')
require('lsp.lua_ls')
require('lsp.pyright')
require('lsp.bashls')
